# Generated by Django 4.2.7 on 2025-11-28 10:22

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tracking_number', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('pickup_address', models.TextField()),
                ('pickup_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_address', models.TextField()),
                ('dropoff_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('dropoff_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('recipient_name', models.CharField(max_length=200)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('recipient_phone', models.CharField(max_length=20)),
                ('recipient_alternate_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('delivery_instructions', models.TextField(blank=True)),
                ('require_recipient_signature', models.BooleanField(default=False)),
                ('parcel_type', models.CharField(choices=[('FOOD', 'Food'), ('ELECTRONICS', 'Electronics'), ('DOCUMENTS', 'Documents'), ('CLOTHING', 'Clothing'), ('PERSONAL_ITEMS', 'Personal Items'), ('MEDICINE', 'Medicine'), ('OTHER', 'Other')], max_length=50)),
                ('parcel_description', models.TextField()),
                ('parcel_condition', models.CharField(max_length=50)),
                ('parcel_quantity', models.PositiveIntegerField(default=1)),
                ('parcel_weight_kg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('parcel_financial_worth', models.DecimalField(decimal_places=2, max_digits=12)),
                ('parcel_images', models.JSONField(blank=True, default=list)),
                ('delivery_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='PENDING', max_length=20)),
                ('courier_payout', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('AVAILABLE', 'Available for Pickup'), ('ASSIGNED', 'Assigned to Courier'), ('ACCEPTED', 'Accepted by Courier'), ('PICKED_UP', 'Picked Up'), ('IN_TRANSIT', 'In Transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('current_location', models.CharField(blank=True, max_length=500)),
                ('estimated_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('offered_to_couriers', models.JSONField(blank=True, default=list)),
                ('offer_expires_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assigned_courier', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'COURIER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(max_length=50)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='orders.order')),
            ],
            options={
                'verbose_name': 'Tracking History',
                'verbose_name_plural': 'Tracking History',
                'db_table': 'tracking_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['order_number'], name='orders_order_n_1336be_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='orders_trackin_cd5d94_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['sender'], name='orders_sender__565a0a_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['assigned_courier'], name='orders_assigne_e4d89f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_status_762191_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='orders_created_77e2b9_idx'),
        ),
    ]
