# Generated by Django 4.2.7 on 2025-10-31 00:03

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='courierprofile',
            name='address',
            field=models.TextField(blank=True, help_text='Courier address', null=True),
        ),
        migrations.AddField(
            model_name='courierprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Courier profile image', null=True, upload_to='profiles/courier/', validators=[apps.accounts.models.validate_image_file]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.TextField(blank=True, help_text='User address', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='User profile image', null=True, upload_to='profiles/user/', validators=[apps.accounts.models.validate_image_file]),
        ),
    ]
