# Generated by Django 4.2.7 on 2025-10-30 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('vehicle_type', models.CharField(choices=[('MOTORCYCLE', 'Motorcycle'), ('CAR', 'Car'), ('VAN', 'Van'), ('TRUCK', 'Truck'), ('BICYCLE', 'Bicycle')], max_length=20)),
                ('ownership_condition', models.CharField(choices=[('OWNED', 'Owned'), ('COMPANY', 'Company'), ('LEASED', 'Leased')], max_length=10)),
                ('manufacturer', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year_of_manufacturing', models.IntegerField()),
                ('license_plate_number', models.CharField(max_length=20, unique=True)),
                ('courier', models.ForeignKey(limit_choices_to={'user_type': 'COURIER'}, on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle',
                'verbose_name_plural': 'Vehicles',
                'db_table': 'vehicles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['courier', 'is_active'], name='vehicles_courier_0b264a_idx'), models.Index(fields=['license_plate_number'], name='vehicles_license_c45f86_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='vehicle',
            constraint=models.UniqueConstraint(fields=('license_plate_number',), name='unique_license_plate'),
        ),
    ]
