# Generated by Django 4.2.7 on 2025-10-30 23:30

import apps.couriers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_policy_proof',
            field=models.FileField(blank=True, help_text='Upload insurance policy proof document (PDF, DOC, DOCX, or Image)', null=True, upload_to='vehicles/documents/insurance/', validators=[apps.couriers.models.validate_document_file]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_proof',
            field=models.FileField(blank=True, help_text='Upload registration proof document (PDF, DOC, DOCX, or Image)', null=True, upload_to='vehicles/documents/registration/', validators=[apps.couriers.models.validate_document_file]),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='road_worthiness_proof',
            field=models.FileField(blank=True, help_text='Upload road worthiness proof document (PDF, DOC, DOCX, or Image)', null=True, upload_to='vehicles/documents/roadworthiness/', validators=[apps.couriers.models.validate_document_file]),
        ),
    ]
