# Generated by Django 4.2.7 on 2025-10-31 00:18

import apps.couriers.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_courierprofile_address_courierprofile_profile_image_and_more'),
        ('couriers', '0002_vehicle_insurance_policy_proof_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('license_number', models.CharField(blank=True, help_text='Driver license number', max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, help_text='Date when license was issued', null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Date when license expires', null=True)),
                ('issuing_authority', models.CharField(blank=True, help_text='Authority that issued the license (e.g., DMV, Transport Authority)', max_length=100, null=True)),
                ('front_page', models.FileField(blank=True, help_text='Driver license front page (PDF, DOC, DOCX, or Image)', null=True, upload_to='licenses/documents/front/', validators=[apps.couriers.models.validate_document_file])),
                ('back_page', models.FileField(blank=True, help_text='Driver license back page (PDF, DOC, DOCX, or Image)', null=True, upload_to='licenses/documents/back/', validators=[apps.couriers.models.validate_document_file])),
                ('courier_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license', to='accounts.courierprofile')),
            ],
            options={
                'verbose_name': 'Driver License',
                'verbose_name_plural': 'Driver Licenses',
                'db_table': 'driver_licenses',
            },
        ),
    ]
