# Generated by Django 4.2.7 on 2025-11-06 14:55

import apps.couriers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0003_driverlicense'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverlicense',
            name='vehicle_insurance',
            field=models.FileField(blank=True, help_text='Vehicle insurance document (PDF, DOC, DOCX, or Image)', null=True, upload_to='licenses/documents/insurance/', validators=[apps.couriers.models.validate_document_file]),
        ),
        migrations.AddField(
            model_name='driverlicense',
            name='vehicle_registration',
            field=models.FileField(blank=True, help_text='Vehicle registration document (PDF, DOC, DOCX, or Image)', null=True, upload_to='licenses/documents/registration/', validators=[apps.couriers.models.validate_document_file]),
        ),
    ]
